// @ts-nocheck
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function GET() {
  const PAGE_W=595.28, PAGE_H=841.89;
  const C={green:[0.2235,0.2706,0.1412],ivory:[0.9647,0.9412,0.898],wine:[0.329,0.114,0.2],gold:[0.722,0.612,0.29],rose:[0.718,0.451,0.49],orange:[0.792,0.482,0.176],ink:[0.13,0.145,0.12],muted:[0.41,0.43,0.38],white:[1,1,1]};
  function esc(s){return s.replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');}
  function rgb(c){return c.map(v=>v.toFixed(4)).join(' ')}
  function text(x,y,size,s,font='F1',color=C.ink){return `${rgb(color)} rg BT /${font} ${size} Tf 1 0 0 1 ${x.toFixed(2)} ${y.toFixed(2)} Tm (${esc(s)}) Tj ET\n`;}
  function rect(x,y,w,h,c){return `${rgb(c)} rg ${x} ${y} ${w} ${h} re f\n`;}
  function line(x1,y1,x2,y2,c=C.green,width=.6){return `${rgb(c)} RG ${width} w ${x1} ${y1} m ${x2} ${y2} l S\n`;}
  function wrap(s,max){const words=s.split(/\s+/), lines=[];let cur='';for(const w of words){const t=cur?cur+' '+w:w;if(t.length>max&&cur){lines.push(cur);cur=w}else cur=t} if(cur)lines.push(cur);return lines;}
  function para(x,y,size,s,maxChars=78,leading=size*1.45,font='F1',color=C.muted){let out=''; for(const l of wrap(s,maxChars)){out+=text(x,y,size,l,font,color);y-=leading;} return {out,y};}
  const svg = await readFile(join(process.cwd(), 'public/brand/vem-viver-logo-master.svg'), 'utf8');
  const m = svg.match(/<path[^>]*\sd="([^"]+)"/s);
  if (!m) throw new Error('Logo path not found');
  const d = m[1];
  function logoPath(){const t=d.trim().split(/\s+/),o=[]; for(let i=0;i<t.length;){const cmd=t[i++]; if(cmd==='M'||cmd==='L'){const x=+t[i++],y=+t[i++];o.push(`${x} ${y} ${cmd==='M'?'m':'l'}`)} else if(cmd==='Z')o.push('h'); else throw new Error(cmd)} return o.join('\n')+'\nf*\n';}
  const LP=logoPath();
  function logo(x,y,w,color=C.green){const s=w/697,h=199*s; return `q ${rgb(color)} rg ${s.toFixed(6)} 0 0 ${(-s).toFixed(6)} ${x.toFixed(2)} ${(y+h).toFixed(2)} cm\n${LP}Q\n`;}
  function footer(n){return line(48,38,547,38,[.82,.82,.78],.4)+text(48,24,7,'Vem Viver · Guia de Marca v1.0 · agosto de 2026','F1',C.muted)+text(532,24,7,String(n).padStart(2,'0'),'F2',C.muted)}
  const pages=[];
  let p='';p+=rect(0,0,PAGE_W,PAGE_H,C.ivory);p+=text(48,790,8,'IDENTIDADE VISUAL · GUIA DE USO','F2',C.muted);p+=logo(60,430,470,C.green);p+=text(60,350,26,'Guia de Marca v1.0','F3',C.green);p+=text(60,316,11,'Referência para comunicação, design, social media, parceiros e registro da marca.','F1',C.muted);p+=line(60,280,535,280,[.74,.74,.68],.5);p+=text(60,255,9,'STATUS','F2',C.gold);p+=text(60,235,14,'Identidade consolidada · ativos vigentes','F2',C.green);p+=footer(1);pages.push(p);
  p='';p+=rect(0,0,PAGE_W,PAGE_H,C.white);p+=text(48,790,8,'01 · LOGOMARCA PRINCIPAL','F2',C.muted);p+=text(48,750,25,'A assinatura é única. Não deve ser recriada.','F3',C.green);p+=rect(48,500,499,180,C.ivory);p+=logo(95,548,405,C.green);p+=text(48,460,10,'Arquivo master','F2',C.gold);p+=text(48,440,13,'vem-viver-logo-master.svg','F2',C.ink);let q=para(48,405,10,'Toda aplicação deve partir do arquivo vetorial oficial. Não redigitar o nome, não aproximar a marca com fontes e não reconstruir letras isoladamente.',72,15);p+=q.out;p+=text(48,305,10,'Versões essenciais','F2',C.gold);p+=rect(48,165,235,110,C.ivory);p+=logo(65,195,200,C.green);p+=rect(312,165,235,110,C.green);p+=logo(329,195,200,C.ivory);p+=text(48,145,8,'POSITIVA · VERDE SOBRE FUNDO CLARO','F2',C.muted);p+=text(312,145,8,'NEGATIVA · MARFIM SOBRE VERDE','F2',C.muted);p+=footer(2);pages.push(p);
  p='';p+=rect(0,0,PAGE_W,PAGE_H,C.ivory);p+=text(48,790,8,'02 · CORES E CONTRASTE','F2',C.muted);p+=text(48,750,23,'O verde sustenta a marca.','F3',C.green);p+=text(48,720,23,'As demais cores organizam o sistema.','F3',C.green);
  const sw=[['Verde Vem Viver','#394524',C.green],['Marfim','#F6F0E5',C.ivory],['Uva tinto','#541D33',C.wine],['Dourado quente','#B89C4A',C.gold],['Rosé','#B7737D',C.rose],['Laranja','#CA7B2D',C.orange]];sw.forEach((a,i)=>{const col=i%3,row=Math.floor(i/3),x=48+col*168,y=610-row*150;p+=rect(x,y,145,82,a[2]);p+=text(x,y-18,9,a[0],'F2',C.ink);p+=text(x,y-33,8,a[1],'F1',C.muted)});
  p+=text(48,305,10,'Contrastes recomendados','F2',C.gold);p+=rect(48,215,230,62,C.green);p+=text(62,241,12,'Vem Viver · marfim sobre verde','F2',C.ivory);p+=rect(317,215,230,62,C.ivory);p+=text(331,241,12,'Vem Viver · verde sobre marfim','F2',C.green);p+=text(48,182,9,'Para textos longos, priorize verde/ink sobre marfim ou marfim sobre verde/vinho.','F1',C.muted);p+=text(48,162,9,'Evite usar dourado como texto pequeno sobre marfim: contraste insuficiente para leitura corrente.','F1',C.muted);p+=footer(3);pages.push(p);
  p='';p+=rect(0,0,PAGE_W,PAGE_H,C.white);p+=text(48,790,8,'03 · TIPOGRAFIA DE APOIO','F2',C.muted);p+=text(48,750,25,'A tipografia apoia. A logomarca permanece intocável.','F3',C.green);p+=text(48,630,34,'Cormorant Garamond','F3',C.green);p+=text(48,600,10,'Uso: títulos, chamadas editoriais e momentos de expressão da marca.','F1',C.muted);p+=line(48,555,547,555,[.82,.82,.78],.5);p+=text(48,500,20,'Manrope','F2',C.green);p+=text(48,472,10,'Uso: textos, informações, navegação, legendas e comunicação funcional.','F1',C.muted);p+=text(48,375,10,'Hierarquia sugerida','F2',C.gold);p+=text(48,340,24,'Título editorial com presença','F3',C.green);p+=text(48,310,12,'Subtítulo claro, direto e sem excesso.','F2',C.ink);p+=text(48,285,9,'Texto de apoio: objetivo, legível e com espaçamento confortável para leitura.','F1',C.muted);p+=text(48,220,9,'Importante: Cormorant Garamond e Manrope são fontes de apoio. Elas não substituem nem recriam o desenho da logomarca.','F1',C.muted);p+=footer(4);pages.push(p);
  p='';p+=rect(0,0,PAGE_W,PAGE_H,C.ivory);p+=text(48,790,8,'04 · RESPIRO E REDUÇÃO','F2',C.muted);p+=text(48,750,25,'Preservar espaço é preservar reconhecimento.','F3',C.green);p+=rect(68,430,459,210,C.white);p+=logo(120,500,355,C.green);p+=line(105,480,490,480,C.gold,.8);p+=text(105,462,8,'ÁREA DE RESPIRO · referência: aproximadamente 1/3 da altura total da marca','F1',C.muted);p+=text(48,340,10,'Redução mínima de referência','F2',C.gold);p+=text(48,310,13,'Digital: 160 px de largura','F2',C.green);p+=text(48,284,13,'Impresso: 28 mm de largura (provisório)','F2',C.green);q=para(48,245,9,'O tamanho mínimo impresso deverá ser revalidado na fase gráfica, de acordo com o processo de impressão, substrato e prova física.',82,14);p+=q.out;p+=footer(5);pages.push(p);
  p='';p+=rect(0,0,PAGE_W,PAGE_H,C.white);p+=text(48,790,8,'05 · USOS INCORRETOS','F2',C.muted);p+=text(48,750,23,'Consistência exige poucas proibições.','F3',C.green);p+=text(48,720,23,'E elas são claras.','F3',C.green);const donts=['Não distorcer, achatar ou alongar a marca.','Não alterar letras ou o V central.','Não mudar cores arbitrariamente.','Não adicionar uvas, folhas, cachos ou símbolos ao logotipo.','Não aplicar sombra, contorno, bevel, gradiente ou brilho.','Não usar a logomarca sobre fundos sem contraste suficiente.','Não redesenhar a marca para registro, impressão ou redes sociais.','Não extrair elementos da logomarca para criar novos ícones sem aprovação.'];let yy=650;donts.forEach((s,i)=>{p+=text(48,yy,9,String(i+1).padStart(2,'0'),'F2',C.gold);p+=text(82,yy,11,s,'F2',C.ink);yy-=58});p+=footer(6);pages.push(p);
  p='';p+=rect(0,0,PAGE_W,PAGE_H,C.green);p+=text(48,790,8,'06 · APLICAÇÕES E PRODUTO','F2',C.gold);p+=text(48,750,23,'A fruta pertence às aplicações.','F3',C.ivory);p+=text(48,720,23,'Não à assinatura da marca.','F3',C.ivory);q=para(48,680,11,'Nos rótulos, materiais digitais e campanhas, uvas, laranjas, texturas e fotografia podem construir o universo do produto. A logomarca, porém, deve permanecer limpa e estável.',72,17,'F1',[.86,.85,.78]);p+=q.out;p+=text(48,560,10,'Representação vigente dos produtos','F2',C.gold);p+=text(48,530,14,'4 sabores × 2 volumes = 8 produtos','F2',C.ivory);p+=text(48,500,10,'Uva Tinto · Uva Branco · Uva Rosé · Laranja','F1',[.86,.85,.78]);p+=text(48,470,10,'1 L · 1,5 L','F1',[.86,.85,.78]);p+=line(48,420,547,420,[.55,.58,.45],.5);p+=text(48,385,10,'Limite técnico','F2',C.gold);q=para(48,355,10,'Os mockups atuais são referência para comunicação e implantação. Eles não substituem os arquivos finais de pré-impressão. Faca, substrato, perfil de cor, dados regulatórios, prova física e acabamentos serão tratados na fase gráfica.',74,15,'F1',[.86,.85,.78]);p+=q.out;p+=footer(7);pages.push(p);
  p='';p+=rect(0,0,PAGE_W,PAGE_H,C.ivory);p+=text(48,790,8,'07 · ENTREGA E GOVERNANÇA','F2',C.muted);p+=text(48,750,23,'Uma única fonte de verdade','F3',C.green);p+=text(48,720,23,'para todos os prestadores.','F3',C.green);p+=text(48,680,10,'Use estes caminhos','F2',C.gold);const links=[['Central de links','https://vemviver.emporioliasch.com.br/links'],['Entrega institucional','https://vemviver.emporioliasch.com.br/entrega'],['Apresentação institucional','https://vemviver.emporioliasch.com.br/institucional'],['Identidade completa','https://vemviver.emporioliasch.com.br/identidade'],['Mockups vigentes','https://vemviver.emporioliasch.com.br/rotulos'],['Master SVG','https://vemviver.emporioliasch.com.br/brand/vem-viver-logo-master.svg']];yy=640;links.forEach(([a,b])=>{p+=text(48,yy,10,a,'F2',C.green);p+=text(190,yy,8,b,'F1',C.muted);yy-=52});p+=text(48,300,10,'Para quem recebe este guia','F2',C.gold);q=para(48,270,10,'Social media, designer, agência, gráfica, fornecedor, parceiro comercial e profissional responsável por registro de marca devem utilizar a master oficial e as regras deste documento. Em caso de dúvida, prevalece a versão online da identidade.',74,15);p+=q.out;p+=logo(325,95,200,C.green);p+=footer(8);pages.push(p);
  function buildPdf(contents){const objs=[];const n=contents.length;objs[1]='<< /Type /Catalog /Pages 2 0 R >>';const pageIds=[],contentIds=[];let next=7;for(let i=0;i<n;i++){pageIds.push(next++);contentIds.push(next++)}objs[2]=`<< /Type /Pages /Kids [${pageIds.map(id=>id+' 0 R').join(' ')}] /Count ${n} >>`;objs[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>';objs[4]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>';objs[5]='<< /Type /Font /Subtype /Type1 /BaseFont /Times-Italic /Encoding /WinAnsiEncoding >>';objs[6]='<< /Type /Font /Subtype /Type1 /BaseFont /Times-Roman /Encoding /WinAnsiEncoding >>';for(let i=0;i<n;i++){objs[pageIds[i]]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_W} ${PAGE_H}] /Resources << /Font << /F1 3 0 R /F2 4 0 R /F3 5 0 R /F4 6 0 R >> >> /Contents ${contentIds[i]} 0 R >>`;const c=contents[i];objs[contentIds[i]]=`<< /Length ${Buffer.byteLength(c,'latin1')} >>\nstream\n${c}endstream`;}
  let out='%PDF-1.4\n%\xE2\xE3\xCF\xD3\n',offs=[0];for(let i=1;i<objs.length;i++){offs[i]=Buffer.byteLength(out,'latin1');out+=`${i} 0 obj\n${objs[i]}\nendobj\n`;}const xref=Buffer.byteLength(out,'latin1');out+=`xref\n0 ${objs.length}\n0000000000 65535 f \n`;for(let i=1;i<objs.length;i++)out+=String(offs[i]).padStart(10,'0')+' 00000 n \n';out+=`trailer\n<< /Size ${objs.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return Buffer.from(out,'latin1');}
  const pdf = buildPdf(pages);
  return new Response(pdf, { headers: { 'Content-Type': 'application/pdf', 'Content-Disposition': 'attachment; filename="Vem_Viver_Guia_de_Marca_v1.pdf"', 'Cache-Control': 'public, max-age=3600' } });
}
